---
title: "Client Report - What's in a Name?"
subtitle: "Unit 1 Task 2"
author: "Tristan Zatylny"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__How does your name at your birth year compare to its use historically? Your must provide a chart. The years labels on your charts should not include a comma.__ 

My name in 2004 has usage pretty similar to the years 1999-2005. There is a large peak in 1996 and it gets very high usage again from 2006-2009.

```{python}
# Q1
(
  ggplot(
    df.filter(name="Tristan"),
    aes("year", "Total")
  )
  + geom_point()
  + geom_line()
  + scale_x_continuous(format=".0f")
  + labs(
    "# of babies named Tristan per year",
    x="Year",
    y="# of babies named Tristan"
  )
)
```


## QUESTION 2

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

I chose Wesley from the Princess Bride. There is a large spike in the name in 1977; the book was published in 1973 and the movie came out in 1987. The movie became available to stream on Disney+ in 2020, but there still does not seem to be any correlation between the movie's release, availability on Disney+, or the book being published and babies being names Wesley.

```{python}
# Q2
(
  ggplot(
    df.filter(name="Wesley"),
    aes("year", "Total")
  )
  + geom_point()
  + geom_line()
  + scale_x_continuous(format=".0f")
  + labs(
    "# of babies named Wesley per year",
    x="Year",
    y="# of babies named Wesley"
  )
)
```

## QUESTION 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__  

Mary was the most popular name by far from 1920-1966. After 1967, the popularity of Mary and Paul declines and is more in line with the other Biblical names. Martha has the most popularity from 1920-1953, after which its usage greatly falls off. Paul sees an increase from 1937-1957 then falls back down from 1958-2000. By 2000, Mary is the most popular baby name with 6,221; 3,791 babies were named Paul, 3,139 were named Peter, and only 750 were named Martha.

```{python}
# Q3
# Linear scale
(
  ggplot(
    df.filter(pl.col("name").is_in(["Mary","Martha", "Peter", "Paul"])),
    aes("year", "Total")
  )
  + geom_point(mapping=aes(color="name"))
  + geom_line(mapping=aes(color="name"))
  + scale_x_continuous(limits=[1920,2000], format=".0f")
  + labs(
    "# of babies with Christian names per year",
    x="Year",
    y="# of babies",
    color="Name"
  )
)
```
```{python}
# Logarithmic scale
(
  ggplot(
    df.filter(pl.col("name").is_in(["Mary","Martha", "Peter", "Paul"])),
    aes("year", "Total")
  )
  + geom_point(mapping=aes(color="name"))
  + geom_line(mapping=aes(color="name"))
  + scale_x_continuous(limits=[1920,2000], format=".0f")
  + scale_y_log10()
  + labs(
    "# of babies with Christian names per year (log scale)",
    x="Year",
    y="# of babies",
    color="Name"
  )
)

```
<!-- Make sure at least one of your charts includes reference marks!! -->