---
title: "Client Report - Flights: Column Aggregation"
subtitle: "Unit 2 Task 2"
author: "Tristan Zatylny"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```


## QUESTION 1

__Calculate the sample size (i.e. number of rows in the dataset) for each airport in each year__. What do you notice?

There are 7 airports in the dataset. Each airport has a sample size of 132 except for Atlanta (ATL), which has a sample size of 109.

```{python}
# Include and execute your code here
sample_size = (df
  .group_by("airport_code")
  .agg(
    pl.col("year").count()
  )
)

sample_size.sort("airport_code")
```

## QUESTION 2

__Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

The airport with the worst delays is the Chicago O'Hare International Airport (ORD). 23% of its flights are delayed, with the average flight delay being 1 hour and 6 minutes. When I see "worst delays", I think of that being "longest delays", so ORD would match that descrption.

```{python}
# Include and execute your code here
delays_df = (df
  .with_columns(
    avg_delay_hours = pl.col("minutes_delayed_total") / pl.col("num_of_delays_total") / 60
  )
  .group_by("airport_code")
  .agg([
    pl.col("num_of_flights_total").sum(),
    pl.col("num_of_delays_total").sum(),
    pl.col("avg_delay_hours").mean()
  ])
  .with_columns(
    proportion_delayed_flights = pl.col("num_of_delays_total") / pl.col("num_of_flights_total")
  )
  .sort(
    "avg_delay_hours",
    descending=True
  )
)

delays_df

```

## QUESTION 3

__Create a barplot showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  

The average proportion of delayed flights across the 7 airports measured is 0.202, meaning that roughly 20% of all flights across these airports are delayed. San Francisco has the highest proportion; 26% of its flights are delayed. Next is Chicago O'Hare with 23%; Atlanta, Denver, San Diego, and Dulles are around 19%; and Salt Lake City has the least at only 14% of its flights being delayed.

```{python}
# Include and execute your code here
plot_data = delays_df.sort("airport_code")
proportion_average = plot_data["proportion_delayed_flights"].mean()
(
ggplot(plot_data, aes("airport_code", "proportion_delayed_flights"))
+ geom_bar(stat="identity", fill="#6164ff", alpha=0.8)
+ geom_hline(yintercept=proportion_average, color="#ff4a4a", linetype="dashed")
+ geom_text(x=1, y=proportion_average+0.01, color="#ff4a4a", label="Average")
+ labs(
    title="Proportion of Delayed Flights by Airport",
    x="Airport Code",
    y="Proportion Delayed"
  )
)

```