---
title: "Client Report - Missing values"
subtitle: "Unit 2 Task 3"
author: "Tristan Zatylny"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```

## QUESTION 1

1. __Convert values to missing__ Start with a fresh copy of the flights dataset by reading it in from the link provided above (as opposed to starting with the dataset you ended with in the last assignment). Identify data values that are problematic, non-sense or impossible and change them to be missing. In your report include one record example (one row) from your clean data, in the raw JSON format. Your example should display at least one missing value so that we can verify it was done correctly. (Note: JSON will convert NaN's to null). Describe your process for finding values that needed to be changed, and how you changed them.

I ran `df.head()` on the data to see if there was any problematic data. I saw that the first row of data contained nonsensical values for *num_of_delays_carrier* and *num_of_delays_late_aircraft*, with their values being "1500+" and -999 respectively. To begin cleaning the data, I cast the *num_of_delays_carrier* column from `str` to `i64`. When doing this, I made sure that `strict` was set to `False` so nonsensical values would just be converted to `null`. I then created a list of all numeric columns in the dataset. I looped through the list using a list comprehension to replace any value less than 0 in a column with `null`. This is the first row of the dataset in JSON format. The values have been changed from the invalid `"1500+"` and `-999` to `null`.

```{python}
# Include and execute your code here
import polars.selectors as cs
import json

numeric_cols = df.select(cs.numeric()).columns
numeric_cols.append("num_of_delays_carrier")

cleaned_df = (df
  # Cast delays_carrier to i64
  .with_columns(
    pl.col("num_of_delays_carrier").cast(pl.Int64, strict=False)
  )
  .with_columns([
    pl.when(pl.col(col) < 0)
    .then(None)
    .otherwise(pl.col(col))
    .alias(col)
    for col in numeric_cols
  ])
)

row_dict = cleaned_df.head(1).to_dicts()[0]
print(json.dumps(row_dict, indent=2))

```

## QUESTION 2

2. __Filling in missing data__ For all the "minutes_delayed" columns, fill in any missing values with the median of that column. For the "num_of" columns, fill in missing values with that column's mean.

```{python}
# Include and execute your code here

filled_df = (cleaned_df
  .with_columns(
    cs.starts_with("minutes_delayed").fill_null(cs.starts_with("minutes_delayed").median())
  )
  .with_columns(
    cs.starts_with("num_of").fill_null(cs.starts_with("num_of").mean())
  )
)

filled_df.head()

```

## QUESTION 3
 
3. __Display a histogram for num_of_delays_carrier and for minutes_delayed_nas (2 separate histograms in total). Comment on the shape of each one. Also report the mean of each of these columns now that missing values have been filled in.__

Both graphs have a skewed right shape. Most of the values are seen on the left; this is especially evident with the Minutes Delayed histogram. The mean of the number of carrier delays is ~700; the mean of the minutes delayed due to NAS is ~70,000.

```{python}
# Include and execute your code here
num_delays_mean = filled_df["num_of_delays_carrier"].mean()

(
ggplot(filled_df, aes("num_of_delays_carrier"))
+ geom_histogram(binwidth=50, fill="#0023a7", alpha=0.7)
+ geom_vline(xintercept=num_delays_mean, color="#ff2828", linetype="dashed")
+ geom_text(x=num_delays_mean+100, y=97, label="Mean", color="#ff2828")
+ labs(
  "Distribution of the Number of Carrier Delays",
  x="# of Carrier Delays",
  y="Frequency (Count)"
  )
)
```

```{python}
min_delayed_mean = filled_df["minutes_delayed_nas"].mean()

(
ggplot(filled_df, aes("minutes_delayed_nas"))
+ geom_histogram(binwidth=10000, fill="#00a738", alpha=0.7)
+ geom_vline(xintercept=min_delayed_mean, color="#ff2828", linetype="dashed")
+ geom_text(x=min_delayed_mean+35000, y=220, label="Mean", color="#ff2828")
+ labs(
  "Distribution of Minutes Delayed due to NAS",
  x="# of Minutes Delayed",
  y="Frequency (Count)"
  )
)

```