---
title: "Client Report -How good is it, really?"
subtitle: "Unit 4 Task 2"
author: "Tristan Zatylny"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import polars.selectors as cs
from sklearn.metrics import (
  accuracy_score,
  precision_score,
  recall_score,
  f1_score,
  confusion_matrix,
  classification_report,
  ConfusionMatrixDisplay
)
from sklearn.inspection import permutation_importance
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# import your data here using polars and the URL
url = "https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv"
df = pl.read_csv(url)

```

## QUESTION 1

1. __Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to define/interpret each of the evaluation metrics you use.  

Evaluation metrics used:

- `Accuracy` - The model's accuracy reports the number of correct answers divided by the total number of test cases. An accuracy of 100% means that the model was always correct. This model achieves an accuracy of 92.341%, meaning it is almost always correct in determining whether or not a house was built before or after 1980.
- `Confusion matrix` - A confusion matrix shows what the model guessed for each data point. It is laid out in the form `[[True Negative | False Positive][False Negative | True Positive]]`. The values on the top left to bottom right diagonal are the amount of times that the model was correct. A perfect model would have all other values be 0; our model got 351/4583 incorrect.
- `F1-score` - The F1-score helps us consider both precision (which is the number of true positives divided by the number of guessed positives `TP/TP+FP`) and recall (which is the number of true positives divided by the number of true positves plus the number of false negatives `TP/TP+FN`) when measuring our model. F1-score is calculated as `(2 * precision * recall) / (precision * recall)`. This would matter more if our dataset was more unbalanced; this value would make it clear whether our model was just guessing that all houses were built before 1980. This model's F1-score is 0.94 for guessing that a house was built before 1980 and 0.90 for guessing that a house was built during or after 1980.

```{python}
# Include and execute your code here
# Don't forget, you need another import statement to import the desired ML model from sklearn

# Remove useless columns (parcel & abstrprd) and giveaways (yrbuilt and answer)
x = df.select(cs.exclude("parcel", "abstrprd", "yrbuilt", "before1980"))

# Choose what we want the model to be predicting
y = df.select("before1980")

# Split training data and seed randomness
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=54321)

# Make random forest
rf_classifier = RandomForestClassifier(random_state=54321)
rf_classifier.fit(x_train, y_train)

# RF prediction
rf_pred = rf_classifier.predict(x_test)
rf_pred

# Classification report for random forest
print("Random Forest")
print(f"Accuracy: {accuracy_score(y_test, rf_pred) * 100:.3f}%")
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))
print("Classification Report:")
print(classification_report(y_test, rf_pred))
```


## QUESTION 2

1. __Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a plot of permutation importance values for the most important features. Were there any features you thought would be importance but weren't?

I originally thought that the most important features would be `arcstyle_ONE-STORY`, `quality_C`, and `sprice`. Two of these three are among the most important; `arcstyle_ONE-STORY` ended up being the second most important, `quality_C` was 10th, and `sprice` wasn't in the top 15. I didn't expect that `numbaths` would be so important nor that `gartype_Att` would be either.

```{python}
# Include and execute your code here
perm = permutation_importance(
  rf_classifier,
  x_test,
  y_test,
  n_repeats=15,
  random_state=54321
)

perm_df = (
  pl.DataFrame(
    {
      "feature": rf_classifier.feature_names_in_,
      "importances": perm.importances_mean
    }
  )
  .sort("importances", descending=True)
)

(
  ggplot(perm_df.head(15), aes("feature", "importances"))
  + geom_bar(stat="identity")
  + labs(
      title="Top Feature Importances",
      x="Feature",
      y="Importance value"
    )
)

```

## QUESTION 3

1. __For the 3 most important features, explain their relationship to the target variable. Use a plot to illustrate the relationship.__ (3 plots minimum)

The three most important features all show clear separation between houses built before and after 1980.

- `gartype_Att` - Houses built before 1980 tend to not have attached garages, with 10,959 out of 14,319 houses built before 1980 not having an attached garage.
- `arcstyle_ONE-STORY` - One-story homes are far more common among houses built before 1980. Of all 8,608 homes marked as being one story, 8,062 were built before 1980.
- `numbaths` - Houses before 1980 tend to have fewer bathrooms. Most houses built before 1980 have 1 or 2 bathrooms; most houses built after 1980 have 2-4 bathrooms.

```{python}
# Get the top 3 features as a list
top3 = perm_df.head(3)["feature"].to_list()

# Cast before1980 as string so the colors can be different for the bar chart
df_plot = df.with_columns(pl.col("before1980").cast(pl.String))

for feature in top3:

  # Get the number of unique values to choose which plot to use
  unique_vals = df[feature].n_unique()

  # Feature's value is either 0 or 1
  if unique_vals <= 2:

    # New dataframe for the plot to get a proportion
    plot_df = (
      df_plot
      .group_by([feature, "before1980"])
      .agg(pl.len().alias("count"))
    )

    # Make a bar chart
    p = (
      ggplot(plot_df, aes(feature, "count", fill="before1980"))
      + geom_bar(stat="identity", position="fill")
      + labs(
        f"{feature} vs. Built Before 1980",
        x=feature,
        y="Proportion",
        fill="Before 1980"
      )
    )

  # Many values for feature (e.g. livearea, sprice)
  else:

    # Make a boxplot
    p = (
      ggplot(df_plot, aes("before1980", feature))
      + geom_boxplot()
      + labs(
        f"{feature} vs. Built Before 1980",
        x="Built Before 1980",
        y=feature
      )
    )

  # Display the plot
  p.show()
```