---
title: "Course Goals Letter (Final)"
subtitle: "Week 14"
author: "Tristan Zatylny"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
execute: 
  warning: false
    
---

# Select Your Target Grade Competency

> **Instructions:** Review the grading tier tables below. The first table in each section shows where you should be **right now** (Week 7) to stay on track. The second table shows where you need to be by **Week 14**. 
> 
> * **Action Required:** Keep the table pair(s) that match your current performance or future goals, and delete the rest. Feel free to mix and match (e.g., if you are currently performing at a B level but aiming for an A by the end of the semester). Please provide an honest assessment!

## Grading Tiers

### A Tier: Leader

**What I have done:**

|        | Grade | Tasks Completed | Stretches | DS Community Tasks | Methods & Calculations @ 100% | Coding Challenge | Course Goal Letter (End) |
|:-------|:-----:|:---------------:|:---------:|:------------------:|:----------------------------:|:----------------:|:-------------------------:|
| Leader |   A   |       18        |    5      |          3         |              6               |         4        |            1              |

**What I need to have done:**

|        | Grade | Tasks (18 Total) | Stretch Tasks (5) | DS Community Tasks | Methods & Calculation Quizzes @ 100% | Coding Challenge | Course Goal Letter (End) |
|:-------|:-----:|:----------------:|:-----------------:|:------------------:|:------------------------------------:|:----------------:|:------------------------:|
| Leader |   A   |      17–18       |       >= 3        | >= 3 (incl. Cert)  |                  6                   |       >= 3       |            1             |

---

## My Letter

### What I have learned
I have learned a lot about analyzing and cleaning data when given a client request. I also learned about different machine learning models and how they can be used directly with data using python.

### Reflection & Progress Report
* **Original Goal:** A
* **Reasoning:** I think that I should get an A for this class. I have completed all of the work in the course, including all tasks, stretch tasks, quizzes, and the coding challenge. I did not get 100% on one of the coding quizzes and I don't have feedback for the coding challenge yet so I'm not sure what my standing is for that either. I think if this class were graded normally, I would get an A.

### Current Standings
* **Tasks Completed:** 18
* **Stretch Tasks Completed:** 5
* **Methods & Calculations Quizzes (at 100%):** 6
* **Coding Challenges:** 4

### Community & Activity Description
The 3 data science community tasks that I have participated in include attending DS society, signing up for a data science newsletter, and getting my bronze certification from the career center.
