---
title: "Client Report - Joins"
subtitle: "Unit 3 Task 3"
author: "Tristan Zatylny"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query that pulls in the the salaries table and the collegeplaying table (and any other tables you might need) and store them in polars dataframes. In Python Polars, combine the dataframes to create a list of baseball players who attended BYU-Idaho. The new table should contain five columns: playerID, schoolID, salary, yearID and teamID associated with each salary.__

There are 3 different players from BYU-I, being catetr01, lindsma01, and stephga01. catetr01 doesn't have any salary linked to them; lindsma01 has 7 rows in the salaries table and stephga01 has 8 rows. lindsma01 has the highest salary at 4,000,000 in 2014 playing for the Chicago White Sox. 

```{python}
# Include and execute your code here
s = """
  SELECT *
  FROM salaries
"""
salaries = pl.read_database(s, con)

c = """
  SELECT *
  FROM collegeplaying
"""
collegeplaying = pl.read_database(c, con)

byui_players = (
    collegeplaying
    .filter(pl.col("schoolID") == "idbyuid")
    .select("playerID", "schoolID")
    .unique()
)

combined_df = (
    salaries
    .join(byui_players, "playerID", "inner")
    .select("playerID", "schoolID", "salary", "yearID", "teamID")
)

combined_df

```


## QUESTION 2

1. Pick any two baseball teams and compare them using a metric of your choice (average salary, home runs, number of wins, etc). Be creative! Write an SQL query to read in the table(s) you need, then use polars to manipulate the data. Finally, make a graph using Lets-Plot to visualize the comparison. What do you learn?

Over the past 25 years in the dataset (1994-2019), the Yankees consistently outperform the Mets in terms of batting averages per year. In 2011, the Mets had a higher batting average than the Yankees, being 0.264 compared to 0.263 for the Yankees. Overall, the difference between them is not too high; the largest gap occured in 1994 with a 0.4 gap in the batting average.

```{python}
# Include and execute your code here

# Comparing team batting averages for each year between the Yankees (NYA) and the Mets (NYN) over the past 25 years

b = """
SELECT *
FROM batting
"""

batting = pl.read_database(b, con, infer_schema_length=None)

t = """
SELECT *
FROM teams
"""

teams = pl.read_database(t, con, infer_schema_length=None)

comp_teams = (
    teams
    .filter(pl.col("teamID").is_in(["NYA", "NYN"]))
    .select("teamID", "name", "yearID")
)

comparison = (
    batting
    .join(comp_teams, "teamID", "inner")
    .select("yearID", "teamID", "name", "H", "AB")
    .group_by(["teamID", "yearID", "name"])
    .agg(
        team_BA = (pl.col("H").sum() / pl.col("AB").sum())
    )
)

(
ggplot(comparison, aes("yearID", "team_BA", color="teamID"))
+ geom_line()
+ coord_cartesian([1994, 2019])
+ scale_x_continuous(format="d")
+ scale_color_manual(
    {"NYA": "navyblue", "NYN": "orange"},
    labels={"NYA": "Yankees", "NYN": "Mets"})
+ labs(
    "Team Batting Average Comparison",
    "Between the Yankees and the Mets over the past 25 years",
    x="Year",
    y="Team Batting Average",
    color="Team"
)
)

```


