---
title: "Client Report - Baseball Database SQL Query"
subtitle: "Unit 3 Task 2"
author: "[STUDENT NAME]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---


```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query that provides playerID, yearID, and batting average for players with at least 1 at bat that year. Sort the table from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

The players aberal01,abernte02, abramge01, acklefr01, alanirj01 all have a batting average of 1.0. This is because they were at bat once and hit the ball, giving them a perfect average.

```{python}
# Include and execute your code here

# The code below can serve as a template for all the rest of your queries. It is just missing the
# SQL code. Put your SQL query in between the triple quotation marks to create the query. The records will be stored in 'results', which is a polars data frame

q = """
    SELECT playerID,
      yearID,
      H,
      AB,
      ROUND((1.0 * H / AB), 3) as batting_avg
    FROM batting
    WHERE AB >= 1
    ORDER BY batting_avg DESC, playerID ASC
    LIMIT 5
    """
results = pl.read_database(q, con)
results

```


## QUESTION 2

__Use the same query as above, but only include players with at least 10 at bats that year. Print the top 5 results.__  

The players with the highest batting average who were at bat 10 or more times are nymanny01 with an average of 0..643, carsoma01 with 0.636, both altizda01 and jognsde01 with 0.6, and silvech01 with 0.571. This only includes players with at least 10 at bats that year.

```{python}
# Include and execute your code here

q = """
    SELECT playerID,
      yearID,
      H,
      AB,
      ROUND((1.0 * H / AB), 3) as batting_avg
    FROM batting
    WHERE AB >= 10
    ORDER BY batting_avg DESC, playerID ASC
    LIMIT 5
    """
results = pl.read_database(q, con)
results

```


## QUESTION 3

__Now modify the SQL query to calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats over their entire career, and print the top 5 results.__

The player with the id cobbty01 has the highest career batting average with 0.366; barnero01 has 0.36, hornsro01 has 0.358, and jacksjo01 and meyerle01 have 0.356. This only includes players who have been at bat at least 100 times across their career.

```{python}
# Include and execute your code here

q = """
    SELECT playerID,
      SUM(H) as career_H,
      SUM(AB) as career_AB,
      ROUND((1.0 * SUM(H) / SUM(AB)), 3) as career_batting_avg
    FROM batting
    GROUP BY playerID
    HAVING SUM(AB) >= 100
    ORDER BY career_batting_avg DESC, playerID ASC
    LIMIT 5
    """
results = pl.read_database(q, con)
results

```