---
title: "Client Report - Baseball Database"
subtitle: "Unit 3 Task 1"
author: "Tristan Zatylny"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

```{python}
# Include and execute your code here

# The code below uses some basic SQL code to read in the entire 'batting' table in the database and store it in a polars dataframe called 'results'. You must write polars code to manipulate the results dataframe to address the task.

q = """
    SELECT *
    FROM batting
    """
results = pl.read_database(q, con, infer_schema_length=None) 
# What does infer_schema_length = None do?
results
```

## QUESTION 1

__Use the provided code above to read in the batting table. Then, with Python Polars manipulate the 'results' dataframe to calculate the number of at bats and the batting average for each year a player played. Filter the data frame to only include players with at least 10 at bats that year. Sort the dataframe from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

Note: A batting average is meant to measure how often a player puts the ball in play and gets to base safely. For this task, use a simplified version of batting average defined as the sum of hits (labeled 'H') divided by number of at bats (labeled 'AB').

The player with the ID nymanny01 has the highest batting average at 0.643, achieving it in 1974. Next is carsoma01 with 0.636 in 2013, then altizda01 and johnsde01 with 0.6 in 1910 and 1975 respectively, and finally silvech01 rounds out the top 5 with a batting average of 0.571 in 1948.

```{python}
# Include and execute your code here
bat_avg_results = (
  results
  .filter(pl.col("AB") >= 10) # At least 10 at bats
  .with_columns(
    batting_avg = (pl.col("H") / pl.col("AB")).round(3) # Caulculate batting avg
  )
  .select("playerID", "yearID", "AB", "batting_avg")
  .sort(["batting_avg", "playerID"], descending=[True, False])
)

bat_avg_results.head(5)

```


## QUESTION 2

__Use the provided code above to read in the batting table. Then, with Python Polars manipulate the 'results' dataframe to calculate the batting average for each player over their entire career (all years combined). Only include players with at least 100 at bats over their entire career. Sort the dataframe from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__ 

Note: A batting average is meant to measure how often a player puts the ball in play and gets to base safely. For this task, use a simplified version of batting average defined as the sum of hits (labeled 'H') divided by number of at bats (labeled 'AB').

The player with the ID cobbty01 has the highest career batting average at 0.366. Next is barnero01 with 0.36, then hornsro01 with 0.358, and finally jacksjo01 and meyerle01 with 0.356.

```{python}
# Include and execute your code here
career_bat_avg = (
  results
  .group_by("playerID") # Each player over their career
  .agg(
    pl.col("AB").sum().alias("Total_AB"), # total AB
    pl.col("H").sum().alias("Total_H") # total hits
  ) 
  .filter(pl.col("Total_AB") >= 100) # At least 100 at bats
  .with_columns(
    career_batting_avg = (pl.col("Total_H") / pl.col("Total_AB")).round(3) # Caulculate batting avg
  )
  .select("playerID", "career_batting_avg")
  .sort(["career_batting_avg", "playerID"], descending=[True, False])
)

career_bat_avg.head(5)

```


